# Numpy Array 

In [3]:
import numpy as np
type(np.array(["Bhavya",2,4]))

numpy.ndarray

In [4]:
type([1,2,3,4,5,6,"Joey","Ross","Chandler"])

list

In [5]:
#upcasting - All will be float
np.array([1,2,3.0])

array([1., 2., 3.])

In [7]:
#two dimension
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
#Minimum dimensions 2
np.array([1,2,3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [10]:
#dtype
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
#Data-type consisting of more than one element:
x = np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])
# (1,2) a=1, b=2 => dtype of a = i2, dtype of b = i8
# (3,4) a=3, b=4 => dtype of a = i2, dtype of b = i8
# i2 -> 16 bit
# i4 -> 32 bit
# i8 -> 64 bit

In [17]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
type(x[1][0])

numpy.int16

In [21]:
type(x)

numpy.ndarray

In [19]:
#Creating an array from sub-classes:
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])

In [20]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray 

In [22]:
#convert the input to an array

In [23]:
#convert a list into an array

In [24]:
a = [1, 2]
type(a)

list

In [25]:
type(np.asarray(a))

numpy.ndarray

In [26]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [27]:
np.asarray((1,2))

array([1, 2])

In [29]:
#If dtype is set, array is copied only if dtype does not match

In [31]:
a = np.array([1,2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [32]:
np.asarray([1,2]) is a

False

In [33]:
np.asarray([1,2])

array([1, 2])

In [34]:
np.asarray(a, dtype=np.float64) is a

False

In [35]:
#ndarray subclasses are not passed through
issubclass(np.matrix, np.ndarray)

True

In [36]:
a = np.matrix([[1,2]])
np.asanyarray(a)

matrix([[1, 2]])

In [37]:
np.asarray(a) is a

False

In [38]:
np.asanyarray(a) is a

True

# numpy.asanyarray 

In [45]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [46]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [47]:
np.array(a)

array([[1, 2]])

In [48]:
np.asarray(a)

array([[1, 2]])

In [49]:
np.asanyarray(a)

matrix([[1, 2]])

In [42]:
np.asanyarray([1,2]) is a

False

In [43]:
#numpy.copy
np.array(a, copy=True)

array([[1, 2]])

In [50]:
#create an array x, with a reference y and a copy z

In [52]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [53]:
y = x

In [54]:
z = np.copy(x)

In [55]:
y[0] = 100
x

array([100,   2,   3])

In [57]:
y

array([100,   2,   3])

In [58]:
z 

array([1, 2, 3])

In [59]:
z[2] = 4

In [60]:
x

array([100,   2,   3])

In [61]:
x[0] = 1

In [62]:
x

array([1, 2, 3])

In [63]:
z

array([1, 2, 4])

# numpy.fromfunction 

In [64]:
#construct an array by executing a function over each coordinate

In [65]:
 np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
np.fromfunction(lambda i, j: i*j, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [67]:
#create a neew 1-dimensional array from an iterable object

In [69]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001C04498D740>

In [70]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [71]:
#A new 1-D array initialized from text data in a string

In [72]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [73]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [74]:
#how to create a record array from a (flat) list of arrays

In [75]:
x1 = np.array([1,2,3,4])

In [76]:
x2 = np.array(['a','dd','xyz','12'])

In [77]:
x3 = np.array([1.1,2,3,4])
x4 = np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [78]:
r = np.core.records.fromarrays([x1,x2,x3,x4], names='a,b,c,d')

In [79]:
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [80]:
print(r[1]["a"])

2


In [81]:
x1[1] = 34

In [84]:
x1

array([ 1, 34,  3,  4])

In [88]:
r[1]['b']

'dd'

# Data type conversion 

In [89]:
my_list = [1,2,3]
arr = np.array(my_list)
print("Type of this object ",type(arr))
print("Here is the vector ",arr)

Type of this object  <class 'numpy.ndarray'>
Here is the vector  [1 2 3]


In [93]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type ",type(mat))
print("Matrix \n-------------\n",mat,'\n-------------')
print("Dimension ",mat.ndim, sep='')
print("Size ",mat.size, sep='')
print("Shape ",mat.shape, sep='')
print("Data type ",mat.dtype, sep='')

Type  <class 'numpy.ndarray'>
Matrix 
-------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-------------
Dimension 2
Size 9
Shape (3, 3)
Data type int32


# arange and linspace 

In [96]:
list(range(4,50,2))

[4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [97]:
np.arange(4,50,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48])

In [98]:
np.arange(4.5,50,2.9)

array([ 4.5,  7.4, 10.3, 13.2, 16.1, 19. , 21.9, 24.8, 27.7, 30.6, 33.5,
       36.4, 39.3, 42.2, 45.1, 48. ])

In [99]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

# Matrix creation 

In [100]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [103]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [104]:
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [105]:
np.logspace(2.0, 3.0, num=4, base=2)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [106]:
#Extract a diagonal or construct a diagonal array
x = np.arange(16).reshape((-1,4))

In [107]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
np.diag(x)

array([ 0,  5, 10, 15])

In [109]:
np.diag(x, k=2)

array([2, 7])

In [110]:
np.diag(x, -2)

array([ 8, 13])

In [112]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [114]:
np.diag(np.diag(x, k=0))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [111]:
#create a two-dimensional array with the flattened input as a diagonal

In [113]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [125]:
a = np.diagflat([[1,2],[3,4]])
for i in a:
    print(i)

[1 0 0 0]
[0 2 0 0]
[0 0 3 0]
[0 0 0 4]


In [115]:
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [116]:
#an array with ones below the given diagonal and zeros elsewhere

In [124]:
np.tri(3,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [118]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [119]:
#return a lower triangle of an array

In [126]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [121]:
#return upper triangle of an array

In [128]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

# Random number generation 

In [130]:
print("Random number generation (from uniform distribution)")
print(np.random.rand(2,3)) #2 by 3 matrix with random numbers from 0 to 1, Note no tuple is necessary

Random number generation (from uniform distribution)
[[0.55148048 0.93395137 0.07569725]
 [0.83505792 0.41607298 0.85656351]]


In [132]:
print("Numbers from Normal Distribution with zero mean and standard distribution 1 i.e. Standard normal")
print(np.random.randn(4,3,5))

Numbers from Normal Distribution with zero mean and standard distribution 1 i.e. Standard normal
[[[ 0.49961902 -1.27276495 -0.09038258 -0.46316012 -0.11090302]
  [-0.61006106  0.4047077   1.65796598  0.40021224 -1.11354463]
  [-0.95919777  0.47851154  1.39058139  0.79901668  0.2228375 ]]

 [[ 2.1164241  -1.57872991  0.14879682 -0.4918983  -0.2315833 ]
  [ 1.26027879  1.66858667 -0.20732738 -0.13761413 -1.86902994]
  [-0.76621121  1.86280399 -0.10428124 -0.61032181  0.48012108]]

 [[ 1.2274617   0.3159731   0.25403777 -0.83347327  0.92540788]
  [-0.62504098 -0.54256276 -0.2367645   0.74918289 -0.43405228]
  [ 2.01346123  1.04373776 -0.89542731 -1.44705212 -2.32092207]]

 [[-1.25595144 -1.57754109  1.0285254   1.18900411 -0.10673396]
  [-1.16037305  0.00309636  0.02633998 -0.29366887 -0.68337695]
  [ 0.25772544  0.53682048  0.02031447 -0.60798886 -0.14952846]]]


In [134]:
print("Raandom integer vector ", np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print("Random integer matrix")
np.random.randint(1,10,5)

Raandom integer vector  8
Random integer matrix


array([9, 7, 5, 1, 6])

In [135]:
print(np.random.randint(1,100,(4,4))) #randint(low, high, # samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw: ", np.random.randint(1,7,20))

[[ 9 74 17 17]
 [93 15 88 41]
 [62 36 57 52]
 [88 88 42 58]]

20 samples drawn from a dice throw:  [3 4 2 6 4 4 5 6 1 3 1 3 1 4 6 5 1 6 6 4]


# Reshaping 

In [136]:
from numpy.random import randint as ri
a = ri(1,100,30)
b= a.reshape(2,3,5)
c= a.reshape(6,-1)
c

array([[66, 13, 71, 31, 61],
       [60, 36, 64, 23, 54],
       [69, 34, 90, 59, 70],
       [22, 84, 73, 34, 78],
       [27, 53, 46, 22, 69],
       [81, 76, 72, 64, 36]])

In [137]:
print("Shape of a: ",a.shape)
print("Shape of b: ",b.shape)
print("Shape of c: ",c.shape)

Shape of a:  (30,)
Shape of b:  (2, 3, 5)
Shape of c:  (6, 5)


In [138]:
A = ri(1,100,10) # vector of random integers
print("\nVector of random integers\n",'-'*50,'\n',A)
print("\nHere is the sorted vector\n",'-'*50,'\n',np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [55 53 96 99 34 81 31 68 11 63]

Here is the sorted vector
 -------------------------------------------------- 
 [11 31 34 53 55 63 68 81 96 99]


In [139]:
M = ri(1,100,25).reshape(5,5) #matrix of random integers
print("\nHere is the sorted matrix along each column\n",'-'*50,'\n',np.sort(M,axis=1,kind='mergesort'))


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 8 26 40 91 99]
 [47 66 69 78 98]
 [31 70 85 86 89]
 [24 54 71 73 78]
 [ 1  1 10 88 96]]


In [142]:
print("Max of a: ",M.max())
print("Max of b: ",b.max())

Max of a:  99
Max of b:  90


In [141]:
b

array([[[66, 13, 71, 31, 61],
        [60, 36, 64, 23, 54],
        [69, 34, 90, 59, 70]],

       [[22, 84, 73, 34, 78],
        [27, 53, 46, 22, 69],
        [81, 76, 72, 64, 36]]])

In [143]:
print("Max of a location:",M.argmax(axis=1))
print("Max of b location:",b.argmax())
print("Max of c location:",c.argmax())

Max of a location: [0 0 0 3 3]
Max of b location: 12
Max of c location: 12


# Indexing and Slicing 

In [144]:
arr = np.arange(0,11)
print("Array",arr)

Array [ 0  1  2  3  4  5  6  7  8  9 10]


In [145]:
print("Element at 7th index is: ",arr[7])

Element at 7th index is:  7


In [146]:
print("Elements from 5rd to 5th index are: ",arr[3:6])

Elements from 5rd to 5th index are:  [3 4 5]


In [147]:
print("Elements up to 4th index are: ",arr[:4])

Elements up to 4th index are:  [0 1 2 3]


# Subseting 

In [148]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat>50

array([[ True, False, False, False, False],
       [False,  True,  True, False,  True],
       [ True,  True, False,  True,  True]])

In [149]:
print("Elements greater than 50\n",mat[mat>50])

Elements greater than 50
 [62 72 55 59 66 54 70 99]


# Universal Functions 

In [150]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print(mat2)

[[1 5 7]
 [2 6 2]
 [5 1 7]]
[[4 7 3]
 [6 6 4]
 [5 9 4]]


In [153]:
mat1*mat2 #static multiplication

array([[ 4, 35, 21],
       [12, 36,  8],
       [25,  9, 28]])

In [154]:
mat1@mat2 #actual matrix multiplication

array([[ 69, 100,  51],
       [ 54,  68,  38],
       [ 61, 104,  47]])

# Broadcasting 

In [155]:
start = np.zeros((4,4))
start = start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [156]:
#create a rank 1 ndarray with 3 values
add_rows = np.array([1,0,2,5])
add_rows

array([1, 0, 2, 5])

In [157]:
y = start+add_rows

In [158]:
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [159]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]
